// Ionicons configuration for tree shaking
// Only imports the icons that are actually used in the app to reduce bundle size

import { addIcons } from 'ionicons';
import {
  add,
  addCircle,
  airplane,
  airplaneOutline,
  alertCircle,
  alertCircleOutline,
  arrowBackOutline,
  arrowDownCircleOutline,
  arrowForward,
  briefcaseOutline,
  arrowForwardCircleOutline,
  arrowForwardOutline,
  business,
  businessOutline,
  calendarClearOutline,
  calendarOutline,
  checkmarkCircle,
  checkmarkDoneCircleOutline,
  chevronBackOutline,
  chevronDownOutline,
  chevronForward,
  chevronForwardOutline,
  clipboardOutline,
  close,
  closeCircle,
  closeCircleOutline,
  closeOutline,
  cloudUploadOutline,
  createOutline,
  documentAttachOutline,
  documentTextOutline,
  downloadOutline,
  eyeOutline,
  handRight,
  handRightOutline,
  idCardOutline,
  informationCircleOutline,
  libraryOutline,
  listOutline,
  locationOutline,
  logInOutline,
  logOutOutline,
  mailOutline,
  people,
  peopleCircleOutline,
  peopleOutline,
  personAdd,
  personAddOutline,
  personCircleOutline,
  personOutline,
  refresh,
  refreshOutline,
  searchOutline,
  settingsOutline,
  shieldCheckmarkOutline,
  sparklesOutline,
  timeOutline,
  trashOutline,
  megaphoneOutline,
  walletOutline,
  pencilOutline,
  layersOutline,
  gitNetworkOutline,
  playCircleOutline,
  receiptOutline,
} from 'ionicons/icons';

// Register all used icons to enable tree shaking
addIcons({
  'add': add,
  'add-circle': addCircle,
  'airplane': airplane,
  'anouncement': megaphoneOutline,
  'airplane-outline': airplaneOutline,
  'alert-circle': alertCircle,
  'alert-circle-outline': alertCircleOutline,
  'arrow-back-outline': arrowBackOutline,
  'arrow-down-circle-outline': arrowDownCircleOutline,
  'arrow-forward': arrowForward,
  'arrow-forward-circle-outline': arrowForwardCircleOutline,
  'arrow-forward-outline': arrowForwardOutline,
  'business': business,
  'business-outline': personCircleOutline,
  'business-icons': people,
  'calendar-clear-outline': calendarClearOutline,
  'calendar-outline': calendarOutline,
  'checkmark-circle': checkmarkCircle,
  'checkmark-done-circle-outline': checkmarkDoneCircleOutline,
  'chevron-back-outline': chevronBackOutline,
  'chevron-down-outline': chevronDownOutline,
  'chevron-forward': chevronForward,
  'chevron-forward-outline': chevronForwardOutline,
  'clipboard-outline': clipboardOutline,
  'close': close,
  'close-circle': closeCircle,
  'close-circle-outline': closeCircleOutline,
  'close-outline': closeOutline,
  'cloud-upload-outline': cloudUploadOutline,
  'create-outline': createOutline,
  'document-attach-outline': documentAttachOutline,
  'document-text-outline': documentTextOutline,
  'download-outline': downloadOutline,
  'eye-outline': eyeOutline,
  'hand-right': handRight,
  'hand-right-outline': handRightOutline,
  'id-card-outline': idCardOutline,
  'information-circle-outline': informationCircleOutline,
  'library-outline': libraryOutline,
  'list-outline': listOutline,
  'location-outline': locationOutline,
  'log-in-outline': logInOutline,
  'log-out-outline': logOutOutline,
  'mail-outline': mailOutline,
  'people': people,
  'people-circle-outline': peopleCircleOutline,
  'people-outline': peopleOutline,
  'person-add': personAdd,
  'person-add-outline': personAddOutline,
  'person-circle-outline': personCircleOutline,
  'person-outline': personOutline,
  'refresh': refresh,
  'refresh-outline': refreshOutline,
  'search-outline': searchOutline,
  'settings-outline': settingsOutline,
  'shield-checkmark-outline': shieldCheckmarkOutline,
  'sparkles-outline': sparklesOutline,
  'time-outline': timeOutline,
  'trash-outline': trashOutline,
  'wallet-outline' : walletOutline,
  'pencil-outline' : pencilOutline,
  'layers-outline': layersOutline,
  'git-network-outline': gitNetworkOutline,
  'play-circle-outline': playCircleOutline,
  'receipt-outline': receiptOutline,
});